version: '2'

services:
  api:
    build: api
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - db
    ports:
      - 8080:5000
    volumes:
      - ./api:/usr/src/app
    command: ["python", "web.py"]

  frontend:
    build: frontend
    ports:
      - 8081:8080
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev"]

  gui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - 8082:8081
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: always
